<a href="https://colab.research.google.com/github/kusumakureti47/Anjali_Al_ML_August_batch_Training/blob/main/Customer_Data_Analysis_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Customer Data Analysis and Data Cleaning

**Name:** Kusuma  
**Roll Number:** VTU32999
**Batch:** AI&ML AUG2026

In [32]:
import pandas as pd
import numpy as np

In [33]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [34]:
df = pd.read_csv("customer_info (2).csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [35]:
original_df = df.copy()

print("Original dataset saved.")

Original dataset saved.

In [36]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 16978
Number of columns: 25

In [37]:
df.head()

,customer_id,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
0,11259,Louis Huffman,male,8/22/1948 5:06,0.0,2.0,2.0,3.0,6238,818,...,1039.0,361,457,1520,210,0.623414,2000,917650.0,38.683897,-9.172942
1,6538,Msc. Noel Ward,male,2/12/1967 19:51,2.0,1.0,3.0,3.0,4188,1048,...,1913.0,562,67,957,92,0.555637,2017,906928.0,38.790490,-9.115064
2,14274,Bsc. Scott Giordano,male,4/10/1986 17:10,0.0,0.0,1.0,1.0,25269,4047,...,303.0,724,442,1213,85,0.259248,2014,958107.0,38.775609,-9.112610
3,7796,William Lacy,male,1/3/1999 1:47,0.0,1.0,1.0,3.0,8292,1524,...,1877.0,560,1028,1005,169,0.419730,2024,967864.0,38.736641,-9.158548
4,4521,Bsc. Nathan Minor,male,10/21/1957 7:34,3.0,1.0,2.0,3.0,43692,3718,...,3093.0,1635,868,745,345,0.428821,2004,971603.0,38.726597,-9.109803

In [38]:
df.tail()

,customer_id,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
16973,13280,Roseann Fiecke,female,3/10/1946 6:44,1.0,2.0,1.0,1.0,36579,3898,...,2934.0,1243,98,1317,406,0.689216,2000,996700.0,38.749251,-9.120427
16974,14100,George Friedmann,male,9/19/1980 14:19,1.0,0.0,1.0,3.0,8575,489,...,581.0,623,408,1367,140,0.550567,2022,907470.0,38.701635,-9.224630
16975,6309,Msc. Michael Rugg,male,2/10/1993 6:13,1.0,0.0,1.0,2.0,17994,2767,...,197.0,711,357,943,158,0.281693,2018,951467.0,38.785835,-9.113974
16976,1000,Bsc. Mary Butler,female,4/7/1978 2:09,0.0,2.0,1.0,3.0,56254,3077,...,2803.0,669,468,423,303,0.117548,2008,997219.0,38.716223,-9.166186
16977,18610,Jeanne Kane,female,8/17/2001 22:49,0.0,0.0,0.0,1.0,4502,1469,...,332.0,437,1605,119,101,0.926938,2019,NaN,38.734891,-9.159710

In [39]:
print("Column names:")
print(df.columns.tolist())

Column names:
['customer_id', 'customer_name', 'customer_gender', 'customer_birthdate', 'kids_home', 'teens_home', 'number_complaints', 'distinct_stores_visited', 'lifetime_spend_groceries', 'lifetime_spend_electronics', 'typical_hour', 'lifetime_spend_vegetables', 'lifetime_spend_nonalcohol_drinks', 'lifetime_spend_alcohol_drinks', 'lifetime_spend_meat', 'lifetime_spend_fish', 'lifetime_spend_hygiene', 'lifetime_spend_videogames', 'lifetime_spend_petfood', 'lifetime_total_distinct_products', 'percentage_of_products_bought_promotion', 'year_first_transaction', 'loyalty_card_number', 'latitude', 'longitude']

In [40]:
df.dtypes

customer_id                                  int64
customer_name                               object
customer_gender                             object
customer_birthdate                          object
kids_home                                  float64
teens_home                                 float64
number_complaints                          float64
distinct_stores_visited                    float64
lifetime_spend_groceries                     int64
lifetime_spend_electronics                   int64
typical_hour                               float64
lifetime_spend_vegetables                  float64
lifetime_spend_nonalcohol_drinks             int64
lifetime_spend_alcohol_drinks              float64
lifetime_spend_meat                          int64
lifetime_spend_fish                        float64
lifetime_spend_hygiene                       int64
lifetime_spend_videogames                    int64
lifetime_spend_petfood                       int64
lifetime_total_distinct_products             int64
percentage_of_products_bought_promotion    float64
year_first_transaction                       int64
loyalty_card_number                        float64
latitude                                   float64
longitude                                  float64
dtype: object

In [41]:
df.describe()

,customer_id,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,typical_hour,lifetime_spend_vegetables,lifetime_spend_nonalcohol_drinks,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
count,16978.000000,16893.000000,16910.000000,16927.000000,16808.000000,16978.000000,16978.000000,16910.000000,16893.000000,16978.000000,...,16808.000000,16978.000000,16978.000000,16978.000000,16978.000000,16978.000000,16978.000000,13835.000000,16978.000000,16978.000000
mean,9981.332195,1.639792,1.085571,1.103917,1.984293,26920.981034,2858.417069,14.665464,2769.181318,2144.302980,...,1715.156592,727.500118,1113.316704,1004.036753,171.656025,0.431158,2014.260101,950299.199060,38.727290,-9.154501
std,5781.604623,1.529161,0.948280,0.920515,1.247115,19734.997961,2404.063138,4.787448,1787.447384,1176.776175,...,1218.002032,499.397645,1558.189418,397.650683,93.932173,0.238567,6.195122,28905.088779,0.037551,0.038855
min,1.000000,0.000000,0.000000,0.000000,1.000000,10.000000,0.000000,6.000000,0.000000,0.000000,...,3.000000,0.000000,0.000000,1.000000,1.000000,-0.438785,1991.000000,900000.000000,38.659915,-9.235972
25%,4973.250000,0.000000,0.000000,0.000000,1.000000,11344.500000,1269.000000,10.000000,1376.000000,1218.000000,...,600.750000,344.000000,398.000000,728.000000,96.000000,0.264496,2011.000000,924926.500000,38.696862,-9.182399
50%,9950.500000,1.000000,1.000000,1.000000,2.000000,20783.500000,2370.000000,15.000000,2423.000000,1999.000000,...,1454.000000,640.000000,642.500000,1003.000000,153.000000,0.407342,2015.000000,950521.000000,38.720024,-9.157290
75%,14999.750000,3.000000,2.000000,2.000000,2.000000,40250.250000,3573.750000,18.000000,3981.000000,2911.750000,...,2611.000000,1017.000000,972.000000,1276.000000,235.000000,0.575179,2019.000000,975177.000000,38.757172,-9.127548
max,20000.000000,11.000000,5.000000,7.000000,10.000000,128132.000000,17407.000000,24.000000,10076.000000,7490.000000,...,6945.000000,3393.000000,11984.000000,2686.000000,592.000000,1.363649,2026.000000,999982.000000,38.809993,-9.064037

#missing value analysis

In [42]:
missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

Missing values in each column:
customer_id                                   0
customer_name                                 0
customer_gender                               0
customer_birthdate                           68
kids_home                                    85
teens_home                                   68
number_complaints                            51
distinct_stores_visited                     170
lifetime_spend_groceries                      0
lifetime_spend_electronics                    0
typical_hour                                 68
lifetime_spend_vegetables                    85
lifetime_spend_nonalcohol_drinks              0
lifetime_spend_alcohol_drinks               170
lifetime_spend_meat                           0
lifetime_spend_fish                         170
lifetime_spend_hygiene                        0
lifetime_spend_videogames                     0
lifetime_spend_petfood                        0
lifetime_total_distinct_products              0
percentage_of_products_bought_promotion       0
year_first_transaction                        0
loyalty_card_number                        3143
latitude                                      0
longitude                                     0
dtype: int64

In [43]:
total_missing = df.isnull().sum().sum()

print("Total missing values:", total_missing)

Total missing values: 4078

In [44]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

print("Missing value percentage:")
print(missing_percentage)

Missing value percentage:
customer_id                                 0.000000
customer_name                               0.000000
customer_gender                             0.000000
customer_birthdate                          0.400518
kids_home                                   0.500648
teens_home                                  0.400518
number_complaints                           0.300389
distinct_stores_visited                     1.001296
lifetime_spend_groceries                    0.000000
lifetime_spend_electronics                  0.000000
typical_hour                                0.400518
lifetime_spend_vegetables                   0.500648
lifetime_spend_nonalcohol_drinks            0.000000
lifetime_spend_alcohol_drinks               1.001296
lifetime_spend_meat                         0.000000
lifetime_spend_fish                         1.001296
lifetime_spend_hygiene                      0.000000
lifetime_spend_videogames                   0.000000
lifetime_spend_petfood                      0.000000
lifetime_total_distinct_products            0.000000
percentage_of_products_bought_promotion     0.000000
year_first_transaction                      0.000000
loyalty_card_number                        18.512192
latitude                                    0.000000
longitude                                   0.000000
dtype: float64

In [45]:
most_missing_column = df.isnull().sum().idxmax()
most_missing_count = df.isnull().sum().max()

print("Column with the highest missing values:", most_missing_column)
print("Number of missing values:", most_missing_count)

Column with the highest missing values: loyalty_card_number
Number of missing values: 3143

#duplicate record analysis

In [46]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate records:", duplicate_count)

Number of duplicate records: 0

customer_name
customer_gender
customer_birthdate

In [47]:
print("Gender values:")
print(df["customer_gender"].value_counts(dropna=False))

Gender values:
customer_gender
female    8580
male      8398
Name: count, dtype: int64

male
Male
MALE

In [48]:
print("Sample customer names:")
print(df["customer_name"].head(20))

Sample customer names:
0              Louis Huffman
1             Msc. Noel Ward
2        Bsc. Scott Giordano
3               William Lacy
4          Bsc. Nathan Minor
5                 Lois Dorko
6             Bsc. John Otis
7         Msc. Dennis Wilber
8                 Ruby Magee
9               Autumn Lloyd
10               Dale Landry
11      Msc. Alberto Palmour
12             Michael Metts
13       Msc. Ruth Hernandez
14                 Doug Gale
15    Bsc. Vincent Duckworth
16               Rita Denmon
17             Kimberly Sova
18         Bsc. Dennis Stone
19       Bsc. Alvin Channell
Name: customer_name, dtype: object

In [49]:
print("Sample birthdates:")
print(df["customer_birthdate"].head(20))

Sample birthdates:
0      8/22/1948 5:06
1     2/12/1967 19:51
2     4/10/1986 17:10
3       1/3/1999 1:47
4     10/21/1957 7:34
5      9/29/2000 4:05
6     7/25/1955 11:49
7     4/18/2000 19:24
8     7/10/1967 20:00
9     8/15/1984 21:40
10     9/27/1994 0:42
11    3/13/1975 21:37
12    11/15/1968 0:11
13     8/6/1954 17:31
14    11/15/1949 5:23
15     6/10/1983 9:00
16    2/24/1949 10:52
17    12/26/1940 9:02
18     2/8/1962 18:16
19    2/13/1952 17:03
Name: customer_birthdate, dtype: object

In [50]:
numeric_columns = df.select_dtypes(include=np.number).columns

print("Numerical columns:")
print(numeric_columns.tolist())

Numerical columns:
['customer_id', 'kids_home', 'teens_home', 'number_complaints', 'distinct_stores_visited', 'lifetime_spend_groceries', 'lifetime_spend_electronics', 'typical_hour', 'lifetime_spend_vegetables', 'lifetime_spend_nonalcohol_drinks', 'lifetime_spend_alcohol_drinks', 'lifetime_spend_meat', 'lifetime_spend_fish', 'lifetime_spend_hygiene', 'lifetime_spend_videogames', 'lifetime_spend_petfood', 'lifetime_total_distinct_products', 'percentage_of_products_bought_promotion', 'year_first_transaction', 'loyalty_card_number', 'latitude', 'longitude']

In [51]:
column = "lifetime_spend_groceries"

Q1 = df[column].quantile(0.25)
Q3 = df[column].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

Q1: 11344.5
Q3: 40250.25
IQR: 28905.75
Lower Bound: -32014.125
Upper Bound: 83608.875

print("Sample customer names:")
print(df["customer_name"].head(20))

In [52]:
outliers = df[
    (df[column] < lower_bound) |
    (df[column] > upper_bound)
]

print("Number of potential outliers:", len(outliers))

Number of potential outliers: 178

In [53]:
values = df["lifetime_spend_groceries"].dropna().to_numpy()

print("Mean:", np.mean(values))
print("Median:", np.median(values))
print("Minimum:", np.min(values))
print("Maximum:", np.max(values))
print("Standard deviation:", np.std(values))

Mean: 26920.981034279655
Median: 20783.5
Minimum: 10
Maximum: 128132
Standard deviation: 19734.416758862088

In [54]:
print("Rows before cleaning:", len(original_df))
print("Rows after cleaning:", len(df))

print("Missing values before cleaning:",
      original_df.isnull().sum().sum())

print("Missing values after cleaning:",
      df.isnull().sum().sum())

print("Duplicates before cleaning:",
      original_df.duplicated().sum())

print("Duplicates after cleaning:",
      df.duplicated().sum())

Rows before cleaning: 16978
Rows after cleaning: 16978
Missing values before cleaning: 4078
Missing values after cleaning: 4078
Duplicates before cleaning: 0
Duplicates after cleaning: 0

#Final Analysis